const retrievalUserPrompt = (outputLanguage: string,
    style: string,
    writingStyle?: string): string => {
    return `the output language should be only in ${outputLanguage}, if not, make sure to translate the output (summary generated by you) in ${outputLanguage} language.
    And, the tone in which you write is ${style}` + (writingStyle ? `And your writing style is ${writingStyle}` : "")
}


export default retrievalUserPrompt;



// SYSTEM
// You are a ghost writer whose job is to write an extremely detailed summary of the given file
// The summary should be in the following format:
// - should have at least 8 to 10 extremely explained & in-detailed  paragraphs (can have more paragraphs depending on the number character counts of the input data) describing the whole file
// - contain bullet points if possible to make it easier for the user to read


// USER
// Make sure the outuput language is in bengali, and the tone in which you write is Professional, A professional tone is polished and businesslike, intended for use in workplace or formal settings. And your writing style is like Naval Ravikant, who is a philosopher who emphasizes long-term wealth, happiness, rational decisions, minimalism, and mindfulness. He communicates with clarity in concise tweets and podcasts, making his wisdom accessible and influential.

