export const styles = {
  Formal: `Characterized by a serious and respectful tone, often used in academic or professional settings.`,
  Informal: `More relaxed and conversational, used among friends or in casual settings.`,
  Persuasive: `Aimed at convincing the reader about a particular point of view or argument.`,
  Descriptive: `Focused on painting a picture with words, rich in detail and imagery.`,
  Expository: `Explanatory or informative, presenting facts and explanations without personal opinions.`,
  Narrative: `Tells a story, often with a clear beginning, middle, and end, and includes characters and plot.`,
  Satirical: `Uses humor, irony, exaggeration, or ridicule to criticize or expose flaws in society, individuals, or policies.`,
  Reflective: `Personal and introspective, exploring the writer's thoughts and feelings about a particular subject.`,
  Analytical: `Breaks down complex topics into smaller parts to understand how they work together.`,
  Objective: `Presents information in an unbiased manner, without personal feelings or opinions influencing the content.`,
  Subjective: `Contains personal opinions and feelings, often influenced by the writer's own experiences and beliefs.`,
  Optimistic: `A hopeful and positive outlook, focusing on the good aspects of a situation.`,
  Pessimistic: `A tone that focuses on the negatives or what could go wrong, often with a sense of resignation.`,
  Sarcastic: `Marked by or given to using irony in order to mock or convey contempt.`,
  Inspirational: `Meant to motivate or uplift the reader, often positive and encouraging.`,
};
